Shippable/beta

- shippable.jobs.yml
- shippable.resources.yml
Shippable/micro#3012
Changes the URL to the new vhost.
> Changes AMQP URL for autod.

- shippable.jobs.yml
- shippable.triggers.yml
> Adds manual deployment trigger.

- shippable.triggers.yml
> Increments trigger.

- shippable.resources.yml
- shippable.triggers.yml
> Re-encrypts RabbitMQ URL.

- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3012
> Re-encrypt amqp url

- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3012
> Add FOO=bar to rabbitMQ params to force deployment

- shippable.resources.yml
- shippable.triggers.yml
> Adds SHIPPABLE_VHOST to man-autod.

- shippable.jobs.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3014
> Add trigger-deploy to deploy-beta-pv2 and increment

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3015
- Moves core.charon to the shippableRoot vhost
> Applies rabbitMQ-params to man-charon; triggers deploys

- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3015
> Trigger deploys

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves versions.trigger to the new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3017
> Move gke to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves DDC to the new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves DCL to the new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves ACS to the new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3023
- Moves barge to shippableRoot vhost
> Move barge to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3027
- Moves nf to shippableRoot vhost
> Move nf to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves Slack to new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves HipChat to new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3030
- Moves irc to shippableRoot vhost
> Move irc to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
> Moves Email to the new vhost.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3033
- Moves hubspotSync to shippableRoot vhost
> Moves hubspotSync to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3034
- Moves sync to shippableRoot vhost
> Move sync to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3026
- Moves ini to the shippableRoot vhost
> Move ini to shippableRoot vhost

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3038
- Moves jobRequest to shippableRoot vhost
> Move jobRequest to shippableRoot vhost

- shippable.resources.yml
> Updates vhost for www.sockets.

- shippable.jobs.yml
- shippable.resources.yml
- shippable.triggers.yml
https://github.com/Shippable/micro/issues/3039
- Moves jobTrigger to shippableRoot vhost
> Move jobTrigger to shippableRoot vhost

- shippable.resources.yml
It shouldn't be in shippable.resources.yml twice.
> Remove extra nexec-img resource.

- shippable.jobs.yml
- shippable.resources.yml
adds webhook for new "server" branch, and builds images on change.
> add api/www/micro server resources and build jobs

- pushRelease.sh
- shippable.jobs.yml
- shippable.resources.yml
This will fix the dependency error in the server release job.
It also adds a script to the runSh job that will re-tag and push images to the prod docker hub repo
> fix rel job and add runSh script

- pushRelease.sh
instead of just echoing for test purposes.
> actually do the docker push

- pushRelease.sh
- shippable.jobs.yml
- shippable.resources.yml
and make some other formatting changes.
> add ecr as push target

- shippable.jobs.yml
- shippable.resources.yml
Resolved https://github.com/Shippable/beta/issues/127
> Add runSh jobs and resources

- shippable.jobs.yml
Fixes https://github.com/Shippable/beta/issues/127
> Add runSh manifest to shippable server release

- shippable.jobs.yml
- shippable.resources.yml
Fixes https://github.com/Shippable/beta/issues/130
> Added jSync to shippable server.

- shippable.resources.yml
https://github.com/Shippable/beta/issues/130
> Updated seed of the jSync image.

- shippable.jobs.yml
- shippable.resources.yml
This should stop everything in Beta.
> Scales Beta to 0.

- shippable.jobs.yml
Restarts Beta for now while leaving the replicas resource to stop it again later.
> Restart Beta.

- shippable.jobs.yml
> Scale Beta to zero.

- shippable.jobs.yml
shut down beta to test upgrade
> reduce to 0 for beta

- shippable.jobs.yml
This will move us from 4.11. to 4.12
> change bump to move to 4.12

- deployAlpha.sh
https://github.com/Shippable/beta/issues/279
> pull base-repo before deploy

- deployQhodeAlpha.sh
- deployQhodeRc.sh
- deployRc.sh
https://github.com/Shippable/beta/issues/298
> Adds pull base repo to server-alpha server-rc and saas-rc

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/319
> add genexec as an image resource

- shippable.jobs.yml
> add genexec image to man-ship

- pushAlpha.sh
- pushFinal.sh
- pushRc.sh
> push genexec to dockerhub for alpha/rc/final

- deployAlpha.sh
- deployQhodeAlpha.sh
This is to fix the 5.2.1 bug we introduced which does not print params file.
> fixing 5.2.1 bug

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/347
> Enables slack notifications for alpha/rc triggers

- tagAndPushImage.sh
- tagAndPushImageRepo.sh
#494 
should be VERSIONNAME not VERSIONANAME
> fix versionname in variable

- tagAndPushImage.sh
- tagAndPushImageRepo.sh
> fix version variable name

- lockUnlockTeams.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/490
> adds lock_team and unlock_team jobs

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/490
> lock teams after build microbase

- lockUnlockTeams.sh
https://github.com/Shippable/beta/issues/503
> do not echo

- lockUnlockTeams.sh
https://github.com/Shippable/beta/issues/508
> fixes typo

- lockUnlockTeams.sh
https://github.com/Shippable/pm/issues/7967
> echo results

- lockUnlockTeams.sh
https://github.com/Shippable/beta/issues/513
> paginate the api calls and also filters forks

- lockUnlockTeams.sh
closes https://github.com/Shippable/beta/issues/515
> handle api call failure

- lockUnlockTeams.sh
https://github.com/Shippable/pm/issues/7967
> get jq returned values as a array instead of string

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/522
> adds resources and jobs to build and push mktg repo

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/524
> adding node repo depndency on api build job

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/526
> trigger deploy rc when mktg image changes

- shippable.jobs.yml
- shippable.resources.yml
- https://github.com/Shippable/buildami/issues/144
> fixing dependency names

- shippable.jobs.yml
- https://github.com/Shippable/buildami/issues/144
> fixing pipeline for building AMI

- shippable.jobs.yml
- https://github.com/Shippable/buildami/issues/144
> fixing link

- lockUnlockTeams.sh
https://github.com/Shippable/beta/issues/534
> Removes pm/heap/support from being locked

- publishDocs.sh
- shippable.jobs.yml
> Add job to publish docs to prod

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/pm/issues/8186
> Use gitRepo instead of ciRepo for docsv2

- publishDocs.sh
https://github.com/Shippable/pm/issues/8186
> Fix publishDocs to use new repo directory

- publishDocs.sh
https://github.com/Shippable/pm/issues/8186
> Fix AWS env names

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/8186
> Add docs job for RC

- check_queue.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/554
> adding check_queue job

- shippable.resources.yml
https://github.com/Shippable/beta/issues/554
> restoring jobTrigger queue limit to 5000

- shippable.resources.yml
https://github.com/Shippable/beta/issues/558
> Passes SHIPPABLE_NODE_INIT_SCRIPT as a param to buildami

- checkQueue.sh
- shippable.resources.yml
https://github.com/Shippable/beta/issues/560
> make queue limits customizable

- shippable.jobs.yml
- shippable.resources.yml
> add basic pipeline jobs for drydock vault

- shippable.jobs.yml
- shippable.resources.yml
> add jobs and resources for gitlab image

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/564
Adds jobs and resources for rabbitmq and redis
> add jobs and resources for rabbitmq and redis

- deployDocs.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/docs/issues/8
> adds job and resources to deploy docs to rcdocs1.shippable.com

- shippable.resources.yml
https://github.com/Shippable/docs/issues/8
> fix bad indentation

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/docs/issues/8
> fix wrong int name && rename resources and jobs to be consistent

- shippable.jobs.yml
> Add temp job for v5.4.1 AMI

- shippable.jobs.yml
- shippable.resources.yml
#578 
This should be it to switch admiral to Docker Hub.
> #578; moves admiral to drydock.

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/8369
This is a precursor to the fix for the PM issue above
> Fixing job names to reduce confusion

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/8369
This created additional params to allow us to downgrade kernel only for specific images. Also cleaned up the hardcoding of init scripts
> adding a flag to decide downgrade of kernel

- lockUnlockTeams.sh
These are not tested using bvt.
> Skip locking of docs, docsv2

- shippable.resources.yml
https://github.com/Shippable/beta/issues/599
> Seed microbase_img with v5.5.3

- shippable.resources.yml
https://github.com/Shippable/beta/issues/599
> Update the seed to master

- shippable.jobs.yml
> Rename docs jobs

- deployRc.sh
> adding admiral upgrade command

- deployRc.sh
> updating directory

- deployRc.sh
> updating command

- deployRc.sh
> testing command variation

- deployRc.sh
> testing command variation 2

- deployRc.sh
> testing command variation 3

- deployRc.sh
> testing command variation 5

- deployRc.sh
> removing commented code

- shippable.jobs.yml
- https://github.com/Shippable/pm/issues/8490
> triggering rc deploy job on admiral image update

- patchImage.sh
- shippable.jobs.yml
> Add job to patch mktg

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/623
> removes old bvt

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/623
> connect bvt-v2 to relprod for better ordering in pipelines

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/626
> adding job to build rc admiral ami

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/626
> adding missing dependency

- shippable.jobs.yml
- shippable.resources.yml
- https://github.com/Shippable/beta/issues/626
> adding ami params

- shippable.resources.yml
- https://github.com/Shippable/beta/issues/626
> updating params

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/627
> adding job for final release of admiral ami

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/627
> adding prod access creds to ami build

- shippable.resources.yml
- https://github.com/Shippable/beta/issues/627
> updating ami params

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/627
> updating admiral final job dependencies

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/642
> fixing execution script

- shippable.jobs.yml
- https://github.com/Shippable/beta/issues/642
> fixing credentials

- shippable.jobs.yml
> Add patch job for v5.6.1 image

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/docs/issues/426
> Add jobs for new/old UI pipelines

- deployDocs.sh
- shippable.jobs.yml
> Fix repo locations

- shippable.jobs.yml
- shippable.resources.yml
For reference: https://github.com/Shippable/docs/issues/426
> Add job to push old and new docs

- deployDocs.sh
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/658
> Updates files to expose different robots.txt file based on runMode

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/623,
https://github.com/Shippable/bvt-v2/pull/65
> Add bvt ghc owner ssh key resource 

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/661
> adds collaborator ssh key integration to yml

- tagAndPushRepo.sh
> use up instead of origin for tag deletion

- tagAndPushBaseRepo.sh
- tagAndPushImageRepo.sh
> fix other scripts to use up instead of origin

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/672
> Updates genexec job to push to drydock repo instead of shipimg

- shippable.jobs.yml
fixes https://github.com/Shippable/beta/issues/675
> add v5.7.3 patch ami job

- tagAndPushAdmiralImageRepo.sh
- tagAndPushImage.sh
- tagAndPushImageRepo.sh
https://github.com/Shippable/beta/issues/676
> Removes -f flag from docker tag as it is not supported anymore

- shippable.resources.yml
https://github.com/Shippable/beta/issues/679
> creates AMI with ubuntu 14.04 and docker 17.06

- shippable.resources.yml
https://github.com/Shippable/test/issues/3196
> Updates RC_SWARM_IP

- shippable.resources.yml
https://github.com/Shippable/pm/issues/8859
> Re-seed version to 5.9.1

- shippable.resources.yml
https://github.com/Shippable/beta/issues/688
> build base_ami using x86_64__Ubuntu__14.04__Docker__17.06.sh

- shippable.resources.yml
Fixes https://github.com/Shippable/beta/issues/691
> Add execTemplates gitRepo

- shippable.jobs.yml
Fixes https://github.com/Shippable/beta/issues/693
> Use execTemplates_repo as an IN to build_micro

- shippable.resources.yml
Fixes https://github.com/Shippable/beta/issues/695
> Add execTemplates_img resource

- shippable.resources.yml
https://github.com/Shippable/beta/issues/695
> Fix rSync error: Add seed section

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/696
> Add job to build execTemplates master image

- buildImage.sh
https://github.com/Shippable/beta/issues/696
> User lowercase name for image

- shippable.jobs.yml
Fixes https://github.com/Shippable/beta/issues/697
> Add a job to tag repo

- shippable.resources.yml
> bump to 5.10 release

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/707
> Create AWS v2 integration for RC

- shippable.resources.yml
https://github.com/Shippable/beta/issues/707
> Remove the old integration for RC access

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/707
> Use AWS v2 for RC docs

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/709
> Update prod docs to use v2 integration

- shippable.resources.yml
https://github.com/Shippable/beta/issues/709
> Remove old cli for aws prod

- shippable.jobs.yml
https://github.com/Shippable/beta/pull/717
> Remove tmp from docs job names

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/719
> Move all runCLI jobs to runSh tmp jobs

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/710
> Config aws v2 integration for ecr push

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/710
> Use aws v2 integration for ami build

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/710
> Update admiral builds to use v2 integration

- shippable.resources.yml
https://github.com/Shippable/beta/issues/710
> Update all images to use new integration

- shippable.resources.yml
Closes https://github.com/Shippable/beta/issues/762
> Add reqExec gitRepo resource

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/763
**Note:** The push to S3 will fail until we have the bucket created and cliConfig added. The rest of it should work.
> Add package_reqExec_x86_64_Ubuntu job

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/763
> Fix script name

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
The bucket has now been created and shipbits ecr has access to it.
https://github.com/Shippable/beta/issues/763
> Add shipbits cli and uncomment S3 push

- repoServices.txt
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/764
> Tag reqExec on release

- shippable.jobs.yml
- tagReqExecArtifact.sh
> Tag reqExec artifact on release

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
- tagReqExecArtifact.sh
https://github.com/Shippable/beta/issues/764
Also, adds public read permission for reqExec binaries.
> Remove region as cli already configures it

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/773
> Add build_reqProc_x86_64_Ubuntu job

- repoServices.txt
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/775
> Add job to tag and push reqproc image

- shippable.jobs.yml
Missed this earlier.
https://github.com/Shippable/beta/issues/773
> Add reqProc as an IN to tag_push_repo

- buildAndPushReqExecArtifacts.sh
https://github.com/Shippable/beta/issues/782
> Remove copy of build.sh

- buildAndPushReqExecArtifacts.sh
https://github.com/Shippable/beta/issues/786
> fix breaking builds for reqExec in pipeline

- buildAndPushReqExecArtifacts.sh
https://github.com/Shippable/reqExec/issues/24
> Use architecture, OS to build package

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
https://github.com/Shippable/beta/issues/790
> Add OS component and cleanup

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
+ Push reqExec artifacts to directory
https://github.com/Shippable/beta/issues/790
> Add dummy jobs for aarch64 Ubuntu 16.04 and x86_64 macOS 10.12

- buildAndPushReqExecArtifacts.sh
- shippable.jobs.yml
> Revert "Add dummy jobs for aarch64 Ubuntu 16.04 and x86_64 macOS 10.12"

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/790
> Add dummy jobs back and remove unnecessary params

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/790
> Fix OS name

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/797
> User new build.sh format

- shippable.jobs.yml
- shippable.resources.yml
Make everything use the new DH integration.
> Update all the jobs to use the new DH int

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/9622
> Build reqExec package for aarch64

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/9623
> Enable macOS jobs

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/9622
https://github.com/Shippable/pm/issues/9623
https://github.com/Shippable/pm/issues/9624
> Enable aarch64 Ubuntu, macOS jobs and minor clean up

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/9622
https://github.com/Shippable/pm/issues/9623
https://github.com/Shippable/pm/issues/9624
> Fix indent

- genBuildImage.sh
https://github.com/Shippable/beta/issues/807
> adds no cache option in docker build

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/809
> update AMI jobs to use strict mode

- buildImage.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/812
> packages aarch64 u16

- buildImage.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/812
Rsync is failing with error ( https://app.shippable.com/github/Shippable/jobs/beta_master_rSync/builds/5a2697f626bb7b07005bab08/console ). So, reverting my changes to unblock others.
> reverting changes to debug

- tagAndPushAdmiralImageRepo.sh
fixes #815 
tested via local script
> update admiral push script for release notes

- buildImage.sh
- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/812
> packages aarch64 16 with different integration

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/818
> packages aarch64 u16pyt

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/819
> packages aarch64 u16cpp

- shippable.jobs.yml
- shippable.resources.yml
https://github.com/Shippable/beta/issues/820
> packages aarch64 microbase

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/820
> adds missing runtime and connects to reqproc

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/820
> connects aarch64 microbase to package reqproc

- shippable.resources.yml
https://github.com/Shippable/beta/issues/827
> changes aarch64 u16cpp to use dry-dock-aarch64

- shippable.resources.yml
https://github.com/Shippable/beta/issues/827
> fix integration and sourceName for aarch64 repos

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/831
https://github.com/Shippable/beta/issues/832
> adds job to build reqExec x86_64 ubuntu14.04

- shippable.jobs.yml
- shippable.resources.yml
- tagAndPushSvcs.sh
https://github.com/Shippable/beta/issues/826
> adds aarch64 ssh keys

- tagAndPushSvcs.sh
https://github.com/Shippable/beta/issues/826
> adds log messages for debugging

- tagAndPushSvcs.sh
https://github.com/Shippable/beta/issues/826
> restructures addition of ssh key

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/838
https://github.com/Shippable/beta/issues/839
> adds job to build reqExec x86_64_CentOS_7

- shippable.jobs.yml
https://github.com/Shippable/beta/issues/839
> adds missing type in jobs

- shippable.jobs.yml
https://github.com/Shippable/pm/issues/9765
> soft deletes deploy_rc job

- shippable.resources.yml
> move to 5.12
