Shippable/beta

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3014
- Moves stepExec services to shippableRoot vhost
- Updates api queue lists accordingly
- Triggers the deploys on api and the stepExec services

Apply rabbitMQ-params to stepExec services

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3020
- Moves triton to the shippableRoot vhost and triggers a deploy

Move triton to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3022
- Moves ECS to shippableRoot vhost

Move ecs to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3024
- Moves certgen to shippableRoot vhost
- Removes trigger-deploy from deploy-beta-pv1, deploy-beta-pv2, and deploy-beta-notify, since we're done updating those services to the new vhost
- Alphabetizes the services in the pv2 applyTo

Move certgen to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3035
- Moves marshaller to shippableRoot vhost
- Alphabetizes deploy-beta-core IN manifests

Move marshaller to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3036
- Moves ec2 to shippableRoot vhost
- Alphabetizes deploy-beta-ci IN manifests

Move ec2 to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml
shippable.triggers.yml

https://github.com/Shippable/micro/issues/3037
- Moves braintree to shippableRoot vhost

Move braintree to shippableRoot vhost

---

shippable.jobs.yml
shippable.resources.yml

Removes RabbitMQ vhost environment variable.

---

shippable.resources.yml

Shippable/nexec#61
Moves `cluster.init` to the list of queues on the new vhost.

Moves cluster.init to the new vhost.

---

shippable.resources.yml

https://github.com/Shippable/www/issues/6906
- Removes VORTEX_QUEUE_LIST and unused queues from api-pararms
The list of queues in beta now reflects the queues in use. VORTEX_QUEUE_LIST is no longer used as well.

Removes VORTEX_QUEUE_LIST and unused queues from api-params

---

shippable.jobs.yml
shippable.resources.yml

https://github.com/Shippable/beta/issues/109
For each stepExec service:
- Updates the JOB_TYPE to remove "Steps"
- Renames the params and manifests to remove "Steps"
- Removes the old queue name (e.g. steps.deploySteps)

Rename stepExec JOB_TYPES and manifests to remove 'Steps' from names

---

shippable.jobs.yml

- set appropriate bump levels
- final release should build off the RC release and use new `bump: final` tag.

restore original bump settings

---

shippable.resources.yml

Fixes #310 
Updates baseami-params to use the latest Ubuntu 14.04 AMI on us-east-1

Update baseami to use latest Ubuntu 14.04

---

shippable.jobs.yml

#450
this will fix the issue of rel-alpha triggering twice for each change to micro-repo.
since OUTs are processed in order, we can simply add `switch: off` to the one that is processed first (micro-img), and let the second one trigger the job.  This will ensure that both images are up to date when rel-alpha runs.

fix double trigger of rel-alpha

---

shippable.jobs.yml
shippable.resources.yml

#492 
only one of the two OUT images will trigger RC. they both get pushed with each change, so this should guarantee latest code is always deployed to rc.
also, setting ship_ver back one so that when rel_prod is run, the correct version is produced.

fix ship_ver so next release is 5.2.4, and fix double rc deploy

---

shippable.jobs.yml
shippable.resources.yml

fixes #562
adds repo/image for admiral, and jobs that will build./push image on repo change, as well as tag/push image when release runs.

add admiral to the pipeline

---

shippable.jobs.yml
shippable.resources.yml

#564
adds a job to push postgres image to drydock master on every change.
when rel-prod is run, pulls master, re-tags as the release version, and pushes the new tag.

add jobs and resources for postgres core service

---

shippable.jobs.yml

This ends up blocking people if we don't know when bvt fails and we don't fix it immediately.

Add notifications for bvt

---

shippable.jobs.yml
shippable.resources.yml

https://github.com/Shippable/heap/issues/846
adds bvt-v2 to pipelines
doesn't block and runs on each commit.

add bvt-v2 to pipelines

---

shippable.jobs.yml

https://github.com/Shippable/beta/issues/621
Since BVT runs into issues frequently, it causes significant time-sink. We'll switch to BVT-2 so we don't run into this. We will still run BVT everyday and before any releases to ensure things are okay. Eventually when BVT-2 catches up with test cases, this will be removed.

Switch off bvt, use bvt-2

---

buildImage.sh

The new SMIs have the drydock master images. This causes a problem while building images.
For eg., if we make any changes to drydock/u14 which triggers drydock/microbase, drydock/microbase will not pull the latest drydock/u14 image since it is already present in the machine.
This PR pulls the latest version of the base image, if present, while building the image.

force pulls latest version of image

---

shippable.jobs.yml

- Picked `buildfinal_ami` id from [lastest job](https://app.shippable.com/github/Shippable/jobs/build_finalami/builds/5991ae36ecc47f0700b827e1/console)
- Verified version from `getSystemMachineImage`
- Also updates scripts to Docker 1.17

add patch job for v5.8.2

---

shippable.jobs.yml

Missed these in the last PR.
https://github.com/Shippable/beta/issues/719

Fix missing deps for build_v561, build_v551, build_v541

---

shippable.jobs.yml

This https://github.com/Shippable/beta/compare/e9919e0a588bb03fdd8dd35724d9198c1a982a9d...shrivara:master might be a better diff to check the changes. Its from the time when the job names were the same.
https://github.com/Shippable/beta/issues/719

Remove tmp suffix from jobs

---

shippable.jobs.yml
shippable.resources.yml

Incorrectly assumed that the ecr integration has access to the buckets as well. The aws integration seems to have full access.
https://github.com/Shippable/beta/issues/763

Use the correct integration for pushing artifact

---

shippable.jobs.yml
shippable.resources.yml

Shippable/heap#1710
fixes indentation for the buildOnCommit flag.
also fixes the double triggering when micro repo has commits.

fix indentation and double micro triggering

---

buildAndPushReqExecArtifacts.sh

https://github.com/Shippable/beta/issues/786
update package.sh path as it was changed in this reqExec issue https://github.com/Shippable/reqExec/issues/20

update package.sh path for reqExec

---

tagAndPushSvcs.sh

https://github.com/Shippable/beta/issues/826
We are doing this because `CONTEXT` is not equal to the docker hub image name and github repo name for aarch64

separates the context and repository name
